name: Build Android APK with Buildozer

on:
  workflow_dispatch: # يخليك تطلق البناء بيدك وقت ما تحب

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build APK with Buildozer Action
      uses: ArtemGovorov/buildozer-action@v1
      id: buildozer
      with:
        workdir: .
        buildozer_version: master

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: smart-shorts-apk
        path: ${{ steps.buildozer.outputs.filename }}
